---
title: "Análisis de Datos"
author: "Tu Nombre"
date: "`r Sys.Date()`"  # Esto insertará la fecha actual
output: html_document
---

# Introducción

Probando el uso de datos en la nube y su publicacion automatica en base a R.
Yanko Goicovic. Unidad de Inteligencia SERNAPESCA.

```{r}
if (!require(httr)) install.packages("httr", dependencies = TRUE)
if (!require(readxl)) install.packages("readxl", dependencies = TRUE)
library(httr)
library(readxl)


# URL del archivo Excel publicado
excel_url <- "https://docs.google.com/spreadsheets/d/e/2PACX-1vSNvzxvxCHOZNa1FlmSHuhm5sqrNz5wOGCMtXYUqRGQ8uBJfaRSvyGFqm4bcihb8myUV7mOXlTtI7wh/pub?output=xlsx"

# Descargar el archivo Excel a un archivo temporal
temp_file <- tempfile(fileext = ".xlsx")
download.file(excel_url, temp_file, mode = "wb")

# Leer el archivo Excel desde el archivo temporal
datos <- read_excel(temp_file)

# Opcionalmente, eliminar el archivo temporal si ya no se necesita
unlink(temp_file)

# Ver los datos
print(datos)

## Calculo simple ####
# Calculando la media de una columna llamada 'PRECIO_KG'
media_PRECIO_KG <- mean(datos$PRECIO_KG, na.rm = TRUE)
print(media_PRECIO_KG)

## Filtrar los datos por la última fecha ##
# Identificar la última fecha
ultima_fecha <- max(datos$FECHA)

# Filtrar los datos para incluir solo la última fecha
datos_ultima_fecha <- datos[datos$FECHA == ultima_fecha, ]

# Imprimir la fecha
print(paste("Fecha:", ultima_fecha))

## Calcular los precios por especie para la última fecha ##
precios_por_especie <- datos_ultima_fecha %>%
  group_by(ESPECIE) %>%
  summarize(PRECIO_KG = mean(PRECIO_KG, na.rm = TRUE),
            PRECIO_CAJA = mean(PRECIO_CAJA, na.rm = TRUE),
            PRECIO_MALLA = mean(PRECIO_MALLA, na.rm = TRUE))

# Presentar los resultados en forma de tabla
knitr::kable(precios_por_especie, caption = "Precios por especie para la última fecha")
